import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { FileSearch, Upload, Check, CircleAlert, Sparkles, FileText, Trash2 } from 'lucide-react';
import { api } from '../api';
import { Heading, Button, Alert, Select, AIConsent, Score, Badge, Loading, technologies, date } from '../components/UI';
export default function Analyzer({ catalog }) {
 const { id } = useParams(), navigate = useNavigate(), input = useRef();
 const [file, setFile] = useState(null), [tech, setTech] = useState(''), [useAI, setUseAI] = useState(false);
 const [doc, setDoc] = useState(null), [history, setHistory] = useState([]), [tab, setTab] = useState('improvements');
 const [error, setError] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(false), [drag, setDrag] = useState(false);
 useEffect(() => { api('/resumes').then(d => setHistory(d.items)).catch(e => setError(e.message)); }, [id]);
 useEffect(() => { setDoc(null); setError(''); if (id) { setLoading(true); api('/resumes/' + id).then(setDoc).catch(e => setError(e.message)).finally(() => setLoading(false)); } }, [id]);
 function choose(f) { if (!f) return; if (!f.name.toLowerCase().endsWith('.pdf') || f.size > 5 * 1024 * 1024) { setError('Choose a PDF smaller than 5 MB.'); return; } setFile(f); setError(''); }
 async function analyze(e) { e.preventDefault(); if (!file) { setError('Choose your PDF first.'); return; } setBusy(true); setError(''); const body = new FormData(); body.append('resume', file); body.append('technology', tech); body.append('use_ai', String(useAI)); try { const data = await api('/resumes', { method: 'POST', body }); setDoc(data); navigate('/analyzer/' + data.id); } catch (e) { setError(e.message); } finally { setBusy(false); } }
 async function remove() { if (!confirm('Delete this analysis report?')) return; try { await api('/resumes/' + id, { method: 'DELETE' }); navigate('/analyzer'); } catch (e) { setError(e.message); } }
 const report = doc?.report;
 return <><Heading eyebrow="YOUR RESUME, WITH A CLEARER DIRECTION" title={report ? 'A clearer picture of your resume.' : 'A stronger resume starts here.'} action={<Badge><Check size={15} /> No job description needed</Badge>}>Find what’s working, fix what’s missing, and make your experience easier to read.</Heading><Alert>{error}</Alert>{loading ? <Loading /> : report ? <>
 <div className="result-toolbar"><div><strong>{doc.filename}</strong><span className="muted"> · {date(doc.created_at)}</span></div><div className="actions"><Button variant="ghost" onClick={remove}><Trash2 size={16} /> Delete report</Button><Button variant="secondary" onClick={() => navigate('/analyzer')}>Analyze another</Button></div></div>
 <div className="analysis-overview"><section className="card score-card"><Score value={report.score} /><div><Badge tone={report.score >= 75 ? 'success' : 'warning'}>{report.score >= 75 ? 'A strong starting point' : 'Room to improve'}</Badge><h2>Every check is a next step.</h2><p className="muted">{report.word_count} words · {report.page_count} {report.page_count === 1 ? 'page' : 'pages'}</p><p className="small muted">{report.notice}</p></div></section><section className="card categories">{report.categories.map(c => <div key={c.name}><span>{c.name}<strong>{c.score}/100</strong></span><div className="bar"><i style={{ width: `${c.score}%` }} /></div></div>)}</section></div>
 <section className="card"><div className="tabs" role="tablist">{[['improvements', 'Improvements'], ['passed', 'Passed checks'], ['skills', 'Skills & keywords']].map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label} {key !== 'skills' && <span>{report.checks.filter(c => c.passed === (key === 'passed')).length}</span>}</button>)}</div>
 {tab === 'skills' ? <div className="keyword-grid"><div><h3>Skills found in your resume</h3><div className="tags">{report.skills.length ? report.skills.map(s => <Badge tone="success" key={s}>{s}</Badge>) : <p>No skills from our technology list were found.</p>}</div></div><div><h3>Terms to consider{report.technology ? ` · ${report.technology}` : ''}</h3><p className="muted small">Include these only when they accurately describe your knowledge. These are suggestions, not required missing skills.</p><div className="tags">{report.suggested_keywords.map(s => <Badge key={s}>{s}</Badge>)}</div></div></div> : <div className="check-list">{report.checks.filter(c => c.passed === (tab === 'passed')).map(c => <div className="check-row" key={c.title}>{c.passed ? <Check className="green" size={20} /> : <CircleAlert className="amber" size={20} />}<div><strong>{c.title}</strong><p>{c.passed ? c.category : c.recommendation}</p></div><Badge tone={c.passed ? 'success' : 'warning'}>{c.passed ? 'PASS' : 'REVIEW'}</Badge></div>)}</div>}
 </section><Alert type="info">{report.ai_notice}</Alert>{report.ai && <section className="card ai-card"><p className="eyebrow"><Sparkles size={16} /> AI RECOMMENDATIONS</p><h2>{report.ai.summary}</h2><ol>{report.ai.recommendations.map((r, i) => <li key={i}>{r}</li>)}</ol><p className="small muted">Generated by {report.source}. Review suggestions before changing your resume.</p></section>}</> : <div className="analyzer-grid"><form className="card upload-card" onSubmit={analyze}><div className="card-heading"><div><h2>Let’s take a look at your resume</h2><p className="muted">Upload your resume as a PDF.</p></div><FileSearch className="blue" /></div><div className={`dropzone ${drag ? 'dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); choose(e.dataTransfer.files[0]); }}><div className="upload-symbol"><FileSearch size={32} /></div><h3>{file ? file.name : 'Drop your resume here'}</h3><p>{file ? `${(file.size / 1024).toFixed(0)} KB · Ready to analyze` : 'or browse files on your device'}</p><Button type="button" variant="secondary" onClick={() => input.current.click()}><Upload size={17} />{file ? 'Change resume' : 'Choose a resume'}</Button><input ref={input} type="file" accept="application/pdf,.pdf" hidden onChange={e => choose(e.target.files[0])} /><small>PDF only · Up to 5 MB · Selectable text</small></div>
 <Select label="Technology focus (optional)" value={tech} onChange={e => setTech(e.target.value)} options={[{ value: '', label: 'Detect from my resume' }, ...technologies]} /><AIConsent checked={useAI} onChange={setUseAI} context="your extracted resume text" provider={catalog?.ai?.resume?.provider} /><Button className="full" busy={busy}><Sparkles size={18} />{busy ? 'Reading and checking your resume…' : 'Analyze my resume'}</Button><p className="form-note">We retain your analysis report, not the uploaded PDF. The score is an estimate of resume readiness.</p></form>
 <aside><section className="insight-panel"><FileSearch size={29} /><p className="eyebrow">CLARITY BEFORE YOU APPLY</p><h2>More than a number.<br /><em>A clear next step.</em></h2><p>Understand each check and decide what to improve.</p><div className="sample-check"><Check size={18} /><span>Clear section headings</span><small>PASS</small></div><div className="sample-check"><CircleAlert size={18} /><span>Show your project’s impact</span><small>REVIEW</small></div><small className="sample-note">An example of the feedback you’ll receive</small></section><section className="card compact-card"><h3>Starting from a blank page?</h3><p className="muted">Choose a clean template and build a resume with your own details.</p><Link to="/builder">Open resume builder</Link></section></aside></div>}
 {history.length > 0 && !report && <section className="card"><h2>Recent analyses</h2><div className="history-list">{history.map(x => <Link to={'/analyzer/' + x.id} key={x.id}><FileText size={18} /><div><strong>{x.filename}</strong><small>{date(x.created_at)}</small></div><Badge>{x.score}/100</Badge></Link>)}</div></section>}
 </>;
}
