import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Download, Save, Plus, Trash2, Check } from 'lucide-react';
import { api, download } from '../api';
import { Heading, Button, Field, Alert, Badge, Loading, Select } from '../components/UI';
const empty = { title: 'My resume', template: 'classic', full_name: '', email: '', phone: '', location: '', links: '', summary: '', skills: [], education: [], experience: [], projects: [], certifications: [] };
const blankEntry = { title: '', organization: '', location: '', start: '', end: '', details: '' };
const templates = [{ id: 'classic', name: 'Classic', description: 'Familiar, focused and easy to scan.' }, { id: 'modern', name: 'Modern', description: 'A subtle blue accent, a clear structure.' }, { id: 'compact', name: 'Compact', description: 'More experience, a little less space.' }];
export default function Builder({ user }) {
 const { id } = useParams(), navigate = useNavigate();
 const [data, setData] = useState({ ...empty, full_name: user.full_name, email: user.email }), [drafts, setDrafts] = useState([]);
 const [busy, setBusy] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
 useEffect(() => { api('/drafts').then(d => setDrafts(d.items)).catch(e => setError(e.message)); if (id) { setLoading(true); api('/drafts/' + id).then(d => setData(d.data)).catch(e => setError(e.message)).finally(() => setLoading(false)); } else setData({ ...empty, full_name: user.full_name, email: user.email }); }, [id]);
 const change = (key, value) => { setData(d => ({ ...d, [key]: value })); setMessage('Unsaved changes'); };
 function entry(section, index, key, value) { change(section, data[section].map((x, i) => i === index ? { ...x, [key]: value } : x)); }
 async function persist() { const d = await api('/drafts' + (id ? '/' + id : ''), { method: id ? 'PUT' : 'POST', body: data }); if (!id) navigate('/builder/' + d.id, { replace: true }); setMessage('Saved to your account'); return d.id; }
 async function save() { setBusy(true); setError(''); try { await persist(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
 async function exportPDF() { setBusy(true); setError(''); try { if (!data.full_name.trim()) throw new Error('Enter your name before downloading.'); const draftId = await persist(); const blob = await api(`/drafts/${draftId}/pdf`, { blob: true }); download(blob, 'skillentra-resume.pdf'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
 async function remove() { if (!id || !confirm('Delete this saved resume?')) return; try { await api('/drafts/' + id, { method: 'DELETE' }); navigate('/builder'); } catch (e) { setError(e.message); } }
 return <><Heading eyebrow="YOUR STORY, CLEARLY PRESENTED" title="A resume that puts you first." action={<Badge><Check size={15} /> Single-column templates</Badge>}>Choose a template. Add your details. Download a clean, selectable-text PDF.</Heading><Alert>{error}</Alert>{loading ? <Loading /> : <>
 <div className="builder-toolbar"><Select label="Saved resumes" value={id || ''} onChange={e => navigate('/builder' + (e.target.value ? '/' + e.target.value : ''))} options={[{ value: '', label: 'Create a new resume' }, ...drafts.map(d => ({ value: d.id, label: d.title }))]} /><div className="actions"><span className="small muted" role="status">{message}</span>{id && <Button variant="ghost" onClick={remove} disabled={busy} aria-label="Delete resume"><Trash2 size={17} /></Button>}<Button variant="secondary" onClick={save} busy={busy}><Save size={17} /> Save</Button><Button onClick={exportPDF} busy={busy}><Download size={17} /> Download PDF</Button></div></div>
 <div className="template-grid">{templates.map(t => <button key={t.id} className={`template-choice ${data.template === t.id ? 'selected' : ''}`} onClick={() => change('template', t.id)} aria-pressed={data.template === t.id}><div className={`mini-page ${t.id}`} aria-hidden="true"><b /><i /><i /><hr /><i /><i /><i /></div><div><strong>{t.name}</strong><p>{t.description}</p></div>{data.template === t.id && <Check size={19} />}</button>)}</div>
 <div className="builder-grid"><div className="builder-form"><section className="card"><p className="eyebrow">01 · THE BASICS</p><h2>Introduce yourself</h2><Field label="Resume title (only for your account)" value={data.title} maxLength={100} onChange={e => change('title', e.target.value)} /><div className="form-grid">{[['full_name', 'Full name'], ['email', 'Email address'], ['phone', 'Phone number'], ['location', 'Location']].map(([key, label]) => <Field key={key} label={label} type={key === 'email' ? 'email' : 'text'} maxLength={200} value={data[key]} onChange={e => change(key, e.target.value)} />)}</div><Field label="Portfolio, GitHub or LinkedIn links" value={data.links} maxLength={800} onChange={e => change('links', e.target.value)} /><Field label="Professional summary"><textarea rows={4} value={data.summary} maxLength={4000} onChange={e => change('summary', e.target.value)} placeholder="Your focus, relevant skills and the value you bring." /></Field><Field label="Skills (separate with commas)"><textarea rows={2} value={data.skills.join(',')} onChange={e => change('skills', e.target.value.split(',').slice(0, 60))} placeholder="Python, Django, React, MongoDB" /></Field></section>
 {['experience', 'projects', 'education'].map((section, s) => <section className="card" key={section}><div className="card-heading"><div><p className="eyebrow">0{s + 2} · YOUR {section.toUpperCase()}</p><h2>{section[0].toUpperCase() + section.slice(1)}</h2></div><Button variant="secondary" onClick={() => change(section, [...data[section], { ...blankEntry }])} disabled={data[section].length >= (section === 'education' ? 10 : 20)}><Plus size={16} /> Add</Button></div>{data[section].length === 0 && <p className="muted small">{section === 'experience' ? 'New to work? Your projects can demonstrate your skills. Add experience when you have it.' : `Add your ${section} details.`}</p>}{data[section].map((x, i) => <div className="entry-form" key={i}><div className="entry-label"><strong>{section === 'education' ? 'Qualification' : section === 'projects' ? 'Project' : 'Experience'} {i + 1}</strong><button className="icon-button" onClick={() => change(section, data[section].filter((_, n) => n !== i))} aria-label={`Remove ${section} ${i + 1}`}><Trash2 size={17} /></button></div><Field label={section === 'education' ? 'Degree or qualification' : section === 'projects' ? 'Project name' : 'Job title'} value={x.title} onChange={e => entry(section, i, 'title', e.target.value)} /><Field label={section === 'education' ? 'College / university' : section === 'projects' ? 'Technology / project link' : 'Company'} value={x.organization} onChange={e => entry(section, i, 'organization', e.target.value)} /><div className="form-grid"><Field label="Start (e.g. Aug 2025)" value={x.start} onChange={e => entry(section, i, 'start', e.target.value)} /><Field label="End (or Present)" value={x.end} onChange={e => entry(section, i, 'end', e.target.value)} /></div><Field label="Location" value={x.location} onChange={e => entry(section, i, 'location', e.target.value)} /><Field label="Details (one bullet per line)"><textarea rows={4} maxLength={4000} value={x.details} onChange={e => entry(section, i, 'details', e.target.value)} placeholder="Describe your contribution and a real outcome." /></Field></div>)}</section>)}
 <section className="card"><h2>Certifications</h2><Field label="One certification per line"><textarea rows={3} value={data.certifications.join('\n')} onChange={e => change('certifications', e.target.value.split('\n').slice(0, 20))} /></Field></section></div>
 <aside className="preview-column"><div className="preview-label"><span>LIVE CONTENT PREVIEW</span><Badge>PDF export may paginate</Badge></div><article className={`resume-paper ${data.template}`}><h1>{data.full_name || 'Your name'}</h1><p className="resume-contact">{[data.email, data.phone, data.location].filter(Boolean).join(' | ')}</p>{data.links && <p className="resume-contact">{data.links}</p>}{data.summary && <><h2>Summary</h2><p>{data.summary}</p></>}{data.skills.some(s => s.trim()) && <><h2>Skills</h2><p>{data.skills.filter(s => s.trim()).join(', ')}</p></>}{['experience', 'projects', 'education'].map(section => data[section].length > 0 && <section key={section}><h2>{section}</h2>{data[section].map((x, i) => <div className="resume-entry" key={i}><h3>{[x.title, x.organization].filter(Boolean).join(' — ') || 'Add details'}</h3><p className="resume-meta">{[x.start, x.end].filter(Boolean).join(' – ')}{x.location && ' | ' + x.location}</p>{x.details && <ul>{x.details.split('\n').filter(Boolean).map((l, j) => <li key={j}>{l.replace(/^[-•]\s*/, '')}</li>)}</ul>}</div>)}</section>)}{data.certifications.some(Boolean) && <><h2>Certifications</h2><ul>{data.certifications.filter(Boolean).map((s, i) => <li key={i}>{s}</li>)}</ul></>}</article><p className="form-note">All three templates use standard headings and one column. The content you add still matters; no template guarantees an ATS score.</p></aside></div></>}</>;
}
