import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CodeXml, Play, Send, Check, CircleX, RotateCcw } from 'lucide-react';
import { api } from '../api';
import { Heading, Button, Alert, Select, AIConsent, Badge, Loading, languages, levels } from '../components/UI';
export default function Coding({ catalog }) {
 const { id } = useParams(), navigate = useNavigate();
 const [language, setLanguage] = useState('Python'), [difficulty, setDifficulty] = useState('easy'), [useAI, setUseAI] = useState(true);
 const [session, setSession] = useState(null), [index, setIndex] = useState(0), [sources, setSources] = useState({}), [submission, setSubmission] = useState(null);
 const [busy, setBusy] = useState(false), [error, setError] = useState('');
 const editor = useRef();
 useEffect(() => { setSession(null); setError(''); setIndex(0); setSubmission(null); if (id) { try { setSources(JSON.parse(sessionStorage.getItem('code:' + id) || '{}')); const last = sessionStorage.getItem('submission:' + id); if (last) setSubmission({ id: last, status: 'pending' }); } catch { setSources({}); } api('/coding/' + id).then(setSession).catch(e => setError(e.message)); } }, [id]);
 useEffect(() => { if (session?.status !== 'validating') return; const interval = setInterval(() => api('/coding/' + id).then(setSession).catch(e => setError(e.message)), 3000); return () => clearInterval(interval); }, [id, session?.status]);
 useEffect(() => { if (submission?.status !== 'pending') return; let alive = true; const check = () => api('/submissions/' + submission.id).then(d => { if (!alive) return; setSubmission(d); if (d.status !== 'pending') { sessionStorage.removeItem('submission:' + id); api('/coding/' + id).then(setSession).catch(e => setError(e.message)); } }).catch(e => { if (alive) setError(e.message); }); check(); const interval = setInterval(check, 2500); return () => { alive = false; clearInterval(interval); }; }, [submission?.id, submission?.status, id]);
 async function start() { setBusy(true); setError(''); try { const s = await api('/coding', { method: 'POST', body: { language, difficulty, use_ai: useAI } }); navigate('/coding/' + s.id); } catch (e) { setError(e.message); } finally { setBusy(false); } }
 const q = session?.questions[index], source = q ? sources[q.id] ?? q.starter : '';
 function edit(value) { const next = { ...sources, [q.id]: value }; setSources(next); try { sessionStorage.setItem('code:' + id, JSON.stringify(next)); } catch { /* Source remains in memory when browser storage is unavailable. */ } }
 function indent(e) { if (e.key !== 'Tab') return; e.preventDefault(); const start = e.target.selectionStart, end = e.target.selectionEnd; edit(source.slice(0, start) + '  ' + source.slice(end)); requestAnimationFrame(() => editor.current.setSelectionRange(start + 2, start + 2)); }
 async function run(mode) { setBusy(true); setError(''); setSubmission(null); try { const d = await api(`/coding/${id}/submissions`, { method: 'POST', body: { question_id: q.id, source, mode } }); setSubmission(d); sessionStorage.setItem('submission:' + id, d.id); } catch (e) { setError(e.message); } finally { setBusy(false); } }
 const running = busy || submission?.status === 'pending';
 return <><Heading eyebrow="LEARN BY SOLVING" title="Three problems. One focused session." action={session?.status === 'ready' && <Button variant="secondary" onClick={() => navigate('/coding')}>New problem set</Button>}>Choose your language and level. Work through the examples, then test your solution.</Heading><Alert>{error}</Alert>{!id ? <div className="setup-grid"><section className="card setup-card"><div className="feature-icon"><CodeXml /></div><h2>Open your coding lab</h2><Select label="Programming language" options={languages} value={language} onChange={e => setLanguage(e.target.value)} /><Select label="Difficulty" options={levels} value={difficulty} onChange={e => setDifficulty(e.target.value)} /><AIConsent checked={useAI} onChange={setUseAI} context="your language and difficulty selection" provider={catalog?.ai?.coding?.provider} /><Button busy={busy} onClick={start}><CodeXml size={18} /> Create 3-question session</Button></section><section className="insight-panel"><p className="eyebrow">FROM AN IDEA TO A WORKING SOLUTION</p><h2>Understand. Write.<br /><em>Test. Improve.</em></h2><ul className="spaced-list"><li>Exactly three questions at your selected level.</li><li>Run the public example while you work.</li><li>Submit against public and hidden test cases.</li><li>AI-generated reference solutions are tested before questions are released.</li></ul><p className="small">Your code and test inputs are sent to the configured isolated Judge0 service. The Django server never runs submitted programs itself.</p></section></div> : !session ? <Loading /> : session.status === 'validating' ? <section className="card"><Loading>Checking generated reference solutions against their test cases…</Loading><p className="muted center">If a generated set fails these checks, you’ll receive a curated problem set.</p></section> : <>
 <Alert type="info">{session.notice}</Alert>{!session.runner_configured && <Alert type="warning">Code execution needs a Judge0 endpoint. The project owner must configure JUDGE0_URL in backend/.env. You can read problems and write solutions now; Run and Submit become available after setup.</Alert>}
 <div className="coding-meta"><Badge>{session.language}</Badge><Badge>{session.difficulty}</Badge><span className="small muted">{session.source}</span></div><div className="problem-tabs">{session.questions.map((x, i) => <button key={x.id} className={index === i ? 'active' : ''} disabled={running} onClick={() => { setIndex(i); setSubmission(null); }}><span>0{i + 1}</span>{x.title}{session.best_scores[x.id] === 100 && <Check size={16} />}</button>)}</div>
 <div className="coding-grid"><section className="card problem-description"><div className="card-heading"><Badge>PROBLEM {index + 1}</Badge><Badge tone={session.best_scores[q.id] === 100 ? 'success' : ''}>Best: {session.best_scores[q.id] ?? 0}%</Badge></div><h2>{q.title}</h2><p>{q.description}</p><h3>Constraints</h3><p className="small muted">{q.constraints}</p><h3>Sample input</h3><pre>{q.example.stdin || '(empty input)'}</pre><h3>Expected output</h3><pre>{q.example.expected}</pre><p className="small muted">One public example + {q.hidden_test_count} hidden tests. Read from standard input and print only the required output.</p></section><section className="code-workspace"><div className="editor-toolbar"><span>{session.language === 'Java' ? 'Main.java' : session.language === 'Python' ? 'solution.py' : session.language === 'C++' ? 'main.cpp' : 'solution.js'}</span><button className="icon-button" onClick={() => { if (confirm('Reset this solution to the starter code?')) edit(q.starter); }} title="Reset starter code" aria-label="Reset starter code"><RotateCcw size={16} /></button></div><textarea ref={editor} className="code-editor" spellCheck="false" aria-label="Code editor" value={source} maxLength={20000} onKeyDown={indent} onChange={e => edit(e.target.value)} /><div className="editor-actions"><span>Draft saved in this browser tab</span><Button variant="secondary" disabled={!session.runner_configured || running} onClick={() => run('run')}><Play size={16} /> Run sample</Button><Button busy={running} disabled={!session.runner_configured} onClick={() => run('submit')}><Send size={16} /> Submit solution</Button></div><div className="execution-results" aria-live="polite"><h3>Test results</h3>{!submission ? <p className="muted">Run your code to see the output here.</p> : submission.status === 'pending' ? <Loading>Running in the isolated judge…</Loading> : submission.status === 'unavailable' ? <Alert type="warning">{submission.message}</Alert> : <><Badge tone={submission.score === 100 ? 'success' : 'warning'}>{submission.mode === 'run' ? 'Sample run' : 'Submission'} · {submission.score}% passed</Badge><div className="test-cases">{submission.results.map(r => <details key={r.case}><summary>{r.passed ? <Check size={17} className="green" /> : <CircleX size={17} className="amber" />}Case {r.case} · {r.public ? 'Public example' : 'Hidden test'}<span>{r.passed ? 'Passed' : r.status}</span></summary>{r.public ? <><h4>Output</h4><pre>{r.stdout || '(no output)'}</pre><h4>Expected</h4><pre>{r.expected}</pre>{r.error && <pre className="error-output">{r.error}</pre>}</> : <p className="small muted">Hidden inputs and outputs stay on the server.</p>}</details>)}</div></>}</div></section></div></>}</>;
}
