import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Trophy, Medal } from 'lucide-react';
import { api } from '../api';
import { Heading, Select, Checkbox, Alert, Loading, Empty, Badge, technologies, clock } from '../components/UI';
export default function Leaderboard({ user, setUser }) {
 const [technology, setTech] = useState('Python'), [data, setData] = useState(null), [error, setError] = useState(''), [saving, setSaving] = useState(false);
 useEffect(() => { setData(null); setError(''); api('/leaderboard?technology=' + encodeURIComponent(technology)).then(setData).catch(e => setError(e.message)); }, [technology, user.leaderboard_opt_in]);
 async function optIn(value) { setSaving(true); try { const d = await api('/auth/me', { method: 'PATCH', body: { leaderboard_opt_in: value } }); setUser(d.user); } catch (e) { setError(e.message); } finally { setSaving(false); } }
 return <><Heading eyebrow="GROW TOGETHER" title="A little friendly competition." action={<Link className="button primary" to="/assessments">Take a ranked test</Link>}>Your best ranked result, alongside others practising the same technology.</Heading><Alert>{error}</Alert><div className="leaderboard-controls"><Select label="Technology" options={technologies} value={technology} onChange={e => setTech(e.target.value)} /><Checkbox checked={user.leaderboard_opt_in} disabled={saving} onChange={e => optIn(e.target.checked)}>Show my name and ranked score on the leaderboard</Checkbox></div><section className="card leaderboard-card"><div className="card-heading"><div className="inline"><Trophy className="blue" /><h2>{technology} leaderboard</h2></div><Badge>Best score per person</Badge></div>{!data && !error ? <Loading /> : !data?.items.length ? <Empty><Trophy size={36} /><h3>Be among the first.</h3><p>No eligible shared scores for {technology} yet. Complete a ranked test and enable leaderboard visibility.</p></Empty> : <div className="table-scroll"><table><thead><tr><th>Rank</th><th>Participant</th><th>Score</th><th>Time</th></tr></thead><tbody>{data.items.map(x => <tr className={x.is_you ? 'you' : ''} key={x.rank}><td><span className={`rank rank-${x.rank}`}>{x.rank <= 3 ? <Medal size={20} /> : '#'} {x.rank}</span></td><td><strong>{x.name}</strong> {x.is_you && <Badge>You</Badge>}</td><td><strong>{x.score}%</strong></td><td>{clock(x.elapsed_seconds)}</td></tr>)}</tbody></table></div>}<p className="form-note">{data?.notice}</p></section><section className="card compact-card"><h3>How ranking works</h3><p className="muted">The ranked challenge uses a shared, versioned question bank. Your best eligible score counts; faster completion breaks ties. AI-generated practice tests and attempts marked for monitoring review do not enter this board.</p><p className="small muted">This community board is for learning. It is not a verified hiring assessment, and the questions can become familiar with practice.</p></section></>;
}
